### ISSUE TITLE
Initial GOBI <-> Koha fields mapping

### ISSUE THREAD

**Issue by kellymc03** [thekesolutions/koha-plugin-gobi#24]
Gobi has three local data fields- can/what fields can be entered in here for Koha to read.  
Thoughts would include location, home/holding branch, item type, note field?

**Comment by tomascohen** [comment]
@kellymc03: about 'Notes', do you think ordernote could be better for the end user? (thinking of how it is displayed in Koha). Maybe we can duplicate that info in both basket AND order line.

**Comment by kellymc03** [comment]
Yes- order notes would be great!  Yes duplicate it!

**Comment by tomascohen** [comment]
Done ;-)
