### ISSUE TITLE
Ability to set statistical fields values

### ISSUE THREAD

**Issue by tomascohen** [thekesolutions/koha-plugin-gobi#35]

**Comment by kellymc03** [comment]
Within the Acquisitions module, up to 2 statistical values can be added to an item.  These statistical values are created in the schema : sort1_authcat and sort2_authcat.  Is it possible to add these values to a Gobi order upon importing.  There would need to be a way to indicate which value would be assigned given the type of record that is coming from Gobi.  For example _ an electronic book would have a value of "ebook" in sort1_authcat and a value of "book" would be added to a print item.  Right now, the code is currently determining where the item is an electronic or print and adding the value of 1 to the 942$n if an ebook to hide from OPAC.
